services:
  - type: web
    name: ai-workflow-builder-backend
    env: python
    rootDir: ai-workflow-builder/server
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: FRONTEND_URL
        value: https://your-frontend.vercel.app
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SERPAPI_API_KEY
        sync: false 